# Generated by Django 4.2.4 on 2023-08-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="company",
        ),
        migrations.RemoveField(
            model_name="question",
            name="job_role",
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tags.questiontype",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="tags.tag"),
        ),
        migrations.AddField(
            model_name="question",
            name="company",
            field=models.ManyToManyField(blank=True, null=True, to="tags.company"),
        ),
        migrations.AddField(
            model_name="question",
            name="job_role",
            field=models.ManyToManyField(blank=True, null=True, to="tags.jobrole"),
        ),
    ]
